name: cart_mate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  connectivity_plus: ^6.1.5
  awesome_snackbar_content: ^0.1.7
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  image: ^4.5.4
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900

flutter_native_splash:
  # The background color for your splash screen.
  color: "#FFF5E9" # White for light mode
  color_dark: "#000000" # A dark color for dark mode

  # The logo to show on the splash screen.
  image: assets/images/logoWithTextpad.png

  android_12:
    image: assets/images/logoWithTextpad.png
    icon_background_color: "#FFF5E9"
    icon_background_color_dark: "#000000"
  fullscreen: true