// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQwk_msiUNzPOg7MTGhMQDD49HpvHOk0',
    appId: '1:8036808949:web:e7eba57043a355e7ee6dbc',
    messagingSenderId: '8036808949',
    projectId: 'cart-mate-704f9',
    authDomain: 'cart-mate-704f9.firebaseapp.com',
    storageBucket: 'cart-mate-704f9.firebasestorage.app',
    measurementId: 'G-T4NFRGV4B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVvspZI3_80vrD526Vd5cszHHmTOapiQE',
    appId: '1:8036808949:android:5a65e8b900f99ef3ee6dbc',
    messagingSenderId: '8036808949',
    projectId: 'cart-mate-704f9',
    storageBucket: 'cart-mate-704f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxZ3aVwu2LeGei8soOGfpLYwaMyZ-t7ek',
    appId: '1:8036808949:ios:2cc5894f7b9c14c6ee6dbc',
    messagingSenderId: '8036808949',
    projectId: 'cart-mate-704f9',
    storageBucket: 'cart-mate-704f9.firebasestorage.app',
    iosBundleId: 'com.example.cartMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxZ3aVwu2LeGei8soOGfpLYwaMyZ-t7ek',
    appId: '1:8036808949:ios:2cc5894f7b9c14c6ee6dbc',
    messagingSenderId: '8036808949',
    projectId: 'cart-mate-704f9',
    storageBucket: 'cart-mate-704f9.firebasestorage.app',
    iosBundleId: 'com.example.cartMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQQwk_msiUNzPOg7MTGhMQDD49HpvHOk0',
    appId: '1:8036808949:web:cf9f1aa6049d3a91ee6dbc',
    messagingSenderId: '8036808949',
    projectId: 'cart-mate-704f9',
    authDomain: 'cart-mate-704f9.firebaseapp.com',
    storageBucket: 'cart-mate-704f9.firebasestorage.app',
    measurementId: 'G-RF9YP1LP34',
  );
}
