// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oAlqCawEpExFuLkabNteDKjpAW7KSWE',
    appId: '1:663503788797:web:6c9db64b26fca309ebfc94',
    messagingSenderId: '663503788797',
    projectId: 'cart-mate-karthi',
    authDomain: 'cart-mate-karthi.firebaseapp.com',
    storageBucket: 'cart-mate-karthi.firebasestorage.app',
    measurementId: 'G-2BXTMT3V7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopYVsso4ZRrCppDPXETKcjde6d8HPm90',
    appId: '1:663503788797:android:f0d9eb256d3d7017ebfc94',
    messagingSenderId: '663503788797',
    projectId: 'cart-mate-karthi',
    storageBucket: 'cart-mate-karthi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJtRUuXqccmieykvRinEfEY0HwtmNEpU',
    appId: '1:663503788797:ios:1eac12d4ba0135deebfc94',
    messagingSenderId: '663503788797',
    projectId: 'cart-mate-karthi',
    storageBucket: 'cart-mate-karthi.firebasestorage.app',
    iosBundleId: 'com.example.cartMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJtRUuXqccmieykvRinEfEY0HwtmNEpU',
    appId: '1:663503788797:ios:1eac12d4ba0135deebfc94',
    messagingSenderId: '663503788797',
    projectId: 'cart-mate-karthi',
    storageBucket: 'cart-mate-karthi.firebasestorage.app',
    iosBundleId: 'com.example.cartMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oAlqCawEpExFuLkabNteDKjpAW7KSWE',
    appId: '1:663503788797:web:679629c6501d64daebfc94',
    messagingSenderId: '663503788797',
    projectId: 'cart-mate-karthi',
    authDomain: 'cart-mate-karthi.firebaseapp.com',
    storageBucket: 'cart-mate-karthi.firebasestorage.app',
    measurementId: 'G-PDP3SQPGBY',
  );

}